name: CustomRecipeGUI
main: net.maple3142.customrecipegui.Main
version: 0.2
commands: 
    recipegui:
        description: create recipe with gui
        usage: /recipegui
permissions:
    customrecipegui.*:
        description: All permissions of CustomRecipeGUI
        children:
            customrecipegui.add: true
            customrecipegui.remove: true
        default: op
    customrecipegui.add:
        description: "CustomRecipeGUI: create recipe"
        default: op
    customrecipegui.remove:
        description: "CustomRecipeGUI: remove recipe"
        default: op
    customrecipegui.preview:
        description: "CustomRecipeGUI: preview recipe"
        default: op
    customrecipegui.edit:
        description: "CustomRecipeGUI: edit recipe"
        default: op
    customrecipegui.list:
        description: "CustomRecipeGUI: list recipes"
        default: op
    customrecipegui.reloadcfg:
        description: "CustomRecipeGUI: reload recipes"
        default: op
    customrecipegui.reloadcfg:
        description: "CustomRecipeGUI: reload config.yml"
        default: op